nombre = input ("ingrese su nombre: ")
edad = int(input ("ingrese su edad: "))
print ("Su nombre es", nombre, "y tiene",edad,"años.")
print ("Su nombre es {} y tiene {} años.".format(nombre,edad))
print ("Ud. tiene {1} años y se llama {0}".format(nombre,edad))# Escribe tu código aquí :-)
